import reflex as rx


rx.page(route="/", title="Home")
def landing() -> rx.Component:
    return rx.fragment(
        rx.box(
            rx.box(
                rx.box(
                    rx.box(
                        rx.flex(
                            rx.flex(
                                rx.el.svg(
                                    rx.el.svg.path(
                                        d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"
                                    ),
                                    rx.el.svg.path(d="M20 3v4"),
                                    rx.el.svg.path(d="M22 5h-4"),
                                    rx.el.svg.path(d="M4 17v2"),
                                    rx.el.svg.path(d="M5 18H3"),
                                    xmlns="http://www.w3.org/2000/svg",
                                    width="1.5rem",
                                    height="1.5rem",
                                    viewbox="0 0 24 24",
                                    fill="none",
                                    stroke="currentColor",
                                    stroke_width="2",
                                    stroke_linecap="round",
                                    stroke_linejoin="round",
                                    class_name="lucide lucide-sparkles",
                                    color="#374151",
                                ),
                                rx.heading(
                                    "SpyGlass Trends",
                                    font_weight="600",
                                    color="#111827",
                                    font_size="1.25rem",
                                    line_height="1.75rem",
                                    as_="h1",
                                ),
                                display="flex",
                                align_items="center",
                                column_gap="0.5rem",
                            ),
                            display="flex",
                            height="4rem",
                            align_items="center",
                            justify_content="flex-start",
                        ),
                        class_name="max-w-[1920px]",
                        margin_left="auto",
                        margin_right="auto",
                        padding_left="1rem",
                        padding_right="1rem",
                    ),
                    background_color="#ffffff",
                    border_bottom_width="1px",
                    height="auto",
                    padding_top="0.5rem",
                    padding_bottom="0.5rem",
                    box_shadow="0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                    position="sticky",
                    top="0",
                    z_index="50",
                ),
                rx.flex(
                    rx.flex(
                        rx.box(
                            rx.box(
                                rx.box(
                                    rx.box(
                                        class_name="recharts-responsive-container",
                                        width="100%",
                                        height="100%",
                                        min_width="0",
                                    ),
                                    class_name="h-[400px]",
                                    aria_label="Growth trends chart: AI in Healthcare grows from 15% in 2025 to 66% in 2030. Green Energy Tech grows from 26% in 2025 to 66% in 2030. Next-Gen AR/VR grows from 25% in 2025 to 103% in 2030. Blockchain Uses grows from 24% in 2025 to 71% in 2030. Robotics Startups grows from 28% in 2025 to 75% in 2030. Space Tech grows from 22% in 2025 to 80% in 2030.",
                                    opacity="0",
                                    transform="translateY(20px) translateZ(0)",
                                ),
                                rx.box(
                                    rx.text(
                                        "Trending Growth Rates (Hover for Details)",
                                        font_size="0.875rem",
                                        line_height="1.25rem",
                                    ),
                                    position="absolute",
                                    background_color="#1F293780",
                                    left="1rem",
                                    padding_left="0.5rem",
                                    padding_right="0.5rem",
                                    padding_top="0.25rem",
                                    padding_bottom="0.25rem",
                                    border_radius="1rem",
                                    color="#ffffff",
                                    top="1rem",
                                ),
                                class_name="h-[250px] sm:h-[400px]",
                                aria_label="Interactive trend chart",
                                position="relative",
                            ),
                            rx.box(
                                rx.heading(
                                    "Discover Trending Opportunities",
                                    font_weight="600",
                                    font_size="1.875rem",
                                    line_height="2.25rem",
                                    color="#111827",
                                    as_="h2",
                                ),
                                rx.text(
                                    "Explore key trends or search your own!",
                                    color="#374151",
                                    font_size="1.125rem",
                                    line_height="1.75rem",
                                ),
                                rx.box(
                                    rx.el.button(
                                        "AI in Healthcare",
                                        class_name="bg-background border-input card-hover-effect disabled:opacity-50 disabled:pointer-events-none focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring hover:text-accent-foreground",
                                        border_width="1px",
                                        font_weight="500",
                                        height="auto",
                                        _hover={"background-color": "#F3F4F6"},
                                        display="inline-flex",
                                        align_items="center",
                                        justify_content="center",
                                        padding_left="1rem",
                                        padding_right="1rem",
                                        padding_top="0.75rem",
                                        padding_bottom="0.75rem",
                                        border_radius="0.375rem",
                                        box_shadow="0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                                        font_size="1rem",
                                        line_height="1.5rem",
                                        color="#374151",
                                        transition_property="color, background-color, border-color, text-decoration-color, fill, stroke",
                                        transition_timing_function="cubic-bezier(0.4, 0, 0.2, 1)",
                                        transition_duration="300ms",
                                        white_space="nowrap",
                                    ),
                                    rx.el.button(
                                        "Green Energy Tech",
                                        class_name="bg-background border-input card-hover-effect disabled:opacity-50 disabled:pointer-events-none focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring hover:text-accent-foreground",
                                        border_width="1px",
                                        font_weight="500",
                                        height="auto",
                                        _hover={"background-color": "#F3F4F6"},
                                        display="inline-flex",
                                        align_items="center",
                                        justify_content="center",
                                        padding_left="1rem",
                                        padding_right="1rem",
                                        padding_top="0.75rem",
                                        padding_bottom="0.75rem",
                                        border_radius="0.375rem",
                                        box_shadow="0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                                        font_size="1rem",
                                        line_height="1.5rem",
                                        color="#374151",
                                        transition_property="color, background-color, border-color, text-decoration-color, fill, stroke",
                                        transition_timing_function="cubic-bezier(0.4, 0, 0.2, 1)",
                                        transition_duration="300ms",
                                        white_space="nowrap",
                                    ),
                                    rx.el.button(
                                        "Next-Gen AR/VR",
                                        class_name="bg-background border-input card-hover-effect disabled:opacity-50 disabled:pointer-events-none focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring hover:text-accent-foreground",
                                        border_width="1px",
                                        font_weight="500",
                                        height="auto",
                                        _hover={"background-color": "#F3F4F6"},
                                        display="inline-flex",
                                        align_items="center",
                                        justify_content="center",
                                        padding_left="1rem",
                                        padding_right="1rem",
                                        padding_top="0.75rem",
                                        padding_bottom="0.75rem",
                                        border_radius="0.375rem",
                                        box_shadow="0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                                        font_size="1rem",
                                        line_height="1.5rem",
                                        color="#374151",
                                        transition_property="color, background-color, border-color, text-decoration-color, fill, stroke",
                                        transition_timing_function="cubic-bezier(0.4, 0, 0.2, 1)",
                                        transition_duration="300ms",
                                        white_space="nowrap",
                                    ),
                                    rx.el.button(
                                        "Blockchain Uses",
                                        class_name="bg-background border-input card-hover-effect disabled:opacity-50 disabled:pointer-events-none focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring hover:text-accent-foreground",
                                        border_width="1px",
                                        font_weight="500",
                                        height="auto",
                                        _hover={"background-color": "#F3F4F6"},
                                        display="inline-flex",
                                        align_items="center",
                                        justify_content="center",
                                        padding_left="1rem",
                                        padding_right="1rem",
                                        padding_top="0.75rem",
                                        padding_bottom="0.75rem",
                                        border_radius="0.375rem",
                                        box_shadow="0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                                        font_size="1rem",
                                        line_height="1.5rem",
                                        color="#374151",
                                        transition_property="color, background-color, border-color, text-decoration-color, fill, stroke",
                                        transition_timing_function="cubic-bezier(0.4, 0, 0.2, 1)",
                                        transition_duration="300ms",
                                        white_space="nowrap",
                                    ),
                                    rx.el.button(
                                        "Robotics Startups",
                                        class_name="bg-background border-input card-hover-effect disabled:opacity-50 disabled:pointer-events-none focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring hover:text-accent-foreground",
                                        border_width="1px",
                                        font_weight="500",
                                        height="auto",
                                        _hover={"background-color": "#F3F4F6"},
                                        display="inline-flex",
                                        align_items="center",
                                        justify_content="center",
                                        padding_left="1rem",
                                        padding_right="1rem",
                                        padding_top="0.75rem",
                                        padding_bottom="0.75rem",
                                        border_radius="0.375rem",
                                        box_shadow="0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                                        font_size="1rem",
                                        line_height="1.5rem",
                                        color="#374151",
                                        transition_property="color, background-color, border-color, text-decoration-color, fill, stroke",
                                        transition_timing_function="cubic-bezier(0.4, 0, 0.2, 1)",
                                        transition_duration="300ms",
                                        white_space="nowrap",
                                    ),
                                    rx.el.button(
                                        "Space Tech",
                                        class_name="bg-background border-input card-hover-effect disabled:opacity-50 disabled:pointer-events-none focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring hover:text-accent-foreground",
                                        border_width="1px",
                                        font_weight="500",
                                        height="auto",
                                        _hover={"background-color": "#F3F4F6"},
                                        display="inline-flex",
                                        align_items="center",
                                        justify_content="center",
                                        padding_left="1rem",
                                        padding_right="1rem",
                                        padding_top="0.75rem",
                                        padding_bottom="0.75rem",
                                        border_radius="0.375rem",
                                        box_shadow="0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                                        font_size="1rem",
                                        line_height="1.5rem",
                                        color="#374151",
                                        transition_property="color, background-color, border-color, text-decoration-color, fill, stroke",
                                        transition_timing_function="cubic-bezier(0.4, 0, 0.2, 1)",
                                        transition_duration="300ms",
                                        white_space="nowrap",
                                    ),
                                    gap="1rem",
                                    display="grid",
                                    grid_template_columns=rx.breakpoints(
                                        {
                                            "0px": "repeat(2, minmax(0, 1fr))",
                                            "640px": "repeat(3, minmax(0, 1fr))",
                                        }
                                    ),
                                    max_width="42rem",
                                    margin_left="auto",
                                    margin_right="auto",
                                ),
                                display="flex",
                                flex_direction="column",
                                margin_top=rx.breakpoints(
                                    {"0px": "1rem", "640px": "0.5rem"}
                                ),
                                gap=rx.breakpoints({"0px": "1.5rem", "640px": "2rem"}),
                                text_align="center",
                            ),
                        ),
                        rx.form(
                            rx.flex(
                                rx.el.button(
                                    rx.el.svg(
                                        rx.el.svg.circle(cx="11", cy="11", r="8"),
                                        rx.el.svg.path(d="m21 21-4.3-4.3"),
                                        xmlns="http://www.w3.org/2000/svg",
                                        width="1.25rem",
                                        height="1.25rem",
                                        viewbox="0 0 24 24",
                                        fill="none",
                                        stroke="currentColor",
                                        stroke_width="2",
                                        stroke_linecap="round",
                                        stroke_linejoin="round",
                                        class_name="lucide lucide-search",
                                    ),
                                    type="submit",
                                    aria_label="Search",
                                    display="flex",
                                    height="2.5rem",
                                    align_items="center",
                                    justify_content="center",
                                    padding_left="0.75rem",
                                    padding_right="0.75rem",
                                    color="#6B7280",
                                ),
                                rx.el.input(
                                    type="text",
                                    placeholder="Search trends...",
                                    aria_label="Search trends...",
                                    value=True,
                                    background_color="transparent",
                                    border_style="none",
                                    flex="1 1 0%",
                                    _focus={"outline-style": "none"},
                                    height="2.5rem",
                                    padding_left="0.25rem",
                                    padding_right="0.25rem",
                                    padding_top="0.5rem",
                                    padding_bottom="0.5rem",
                                    color="#111827",
                                ),
                                background_color="#ffffff",
                                border_width="1px",
                                border_color="#D1D5DB",
                                transition_duration="300ms",
                                display="flex",
                                align_items="center",
                                overflow="hidden",
                                border_radius="0.5rem",
                                transition_property="all",
                                transition_timing_function="cubic-bezier(0.4, 0, 0.2, 1)",
                            ),
                            rx.box(
                                "Try searching for AI, Healthcare, Blockchain...",
                                display=rx.breakpoints({"0px": "none", "640px": "block"}),
                                margin_left="0.5rem",
                                margin_top="0.25rem",
                                color="#6B7280",
                                font_size="0.75rem",
                                line_height="1rem",
                            ),
                            class_name="!mb-1 SearchInput group",
                            role="search",
                            position="relative",
                        ),
                        display="flex",
                        flex="1 1 0%",
                        flex_direction="column",
                        justify_content="space-between",
                        max_width="56rem",
                        padding_bottom="0",
                        width="100%",
                    ),
                    class_name="bg-gradient-to-b custom-min-height from-gray-50 to-gray-200",
                    display="flex",
                    flex_direction="column",
                    align_items="center",
                    padding_left="1rem",
                    padding_right="1rem",
                    padding_top="1.5rem",
                    padding_bottom="1.5rem",
                ),
                class_name="mobile-full-height",
                background_color="#F9FAFB",
                min_height="100vh",
            ),
            rx.script(
                src="/_next/static/chunks/webpack-1e037fdc96d674db.js",
                strategy="afterInteractive",
            ),
            rx.script(
                """(self.__next_f=self.__next_f||[]).push([0]);self.__next_f.push([2,null])"""
            ),
            rx.script(
                """self.__next_f.push([1,"1:HL[\"/_next/static/media/e11418ac562b8ac1-s.p.woff2\",\"font\",{\"crossOrigin\":\"\",\"type\":\"font/woff2\"}]\n2:HL[\"/_next/static/css/070b68d383b0d950.css\",\"style\"]\n3:HL[\"/_next/static/css/e4f64c78e7c73b05.css\",\"style\"]\n"])"""
            ),
            rx.script(
                """self.__next_f.push([1,"4:I[2846,[],\"\"]\n6:I[9107,[],\"ClientPageRoot\"]\n7:I[6778,[\"415\",\"static/chunks/415-8c523922821b0baa.js\",\"931\",\"static/chunks/app/page-42684194f535faca.js\"],\"default\",1]\n8:I[4707,[],\"\"]\n9:I[6423,[],\"\"]\nb:I[1060,[],\"\"]\nc:[]\n"])"""
            ),
            rx.script(
                """self.__next_f.push([1,"0:[\"$\",\"$L4\",null,{\"buildId\":\"FXJ1t7dK3wx9XfhoIxOIc\",\"assetPrefix\":\"\",\"urlParts\":[\"\",\"\"],\"initialTree\":[\"\",{\"children\":[\"__PAGE__\",{}]},\"$undefined\",\"$undefined\",true],\"initialSeedData\":[\"\",{\"children\":[\"__PAGE__\",{},[[\"$L5\",[\"$\",\"$L6\",null,{\"props\":{\"params\":{},\"searchParams\":{}},\"Component\":\"$7\"}],[[\"$\",\"link\",\"0\",{\"rel\":\"stylesheet\",\"href\":\"/_next/static/css/e4f64c78e7c73b05.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}]]],null],null]},[[[[\"$\",\"link\",\"0\",{\"rel\":\"stylesheet\",\"href\":\"/_next/static/css/070b68d383b0d950.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}]],[\"$\",\"html\",null,{\"lang\":\"en\",\"suppressHydrationWarning\":true,\"children\":[\"$\",\"body\",null,{\"className\":\"min-h-screen bg-background font-sans antialiased __className_3a0388\",\"children\":[\"$\",\"$L8\",null,{\"parallelRouterKey\":\"children\",\"segmentPath\":[\"children\"],\"error\":\"$undefined\",\"errorStyles\":\"$undefined\",\"errorScripts\":\"$undefined\",\"template\":[\"$\",\"$L9\",null,{}],\"templateStyles\":\"$undefined\",\"templateScripts\":\"$undefined\",\"notFound\":[[\"$\",\"title\",null,{\"children\":\"404: This page could not be found.\"}],[\"$\",\"div\",null,{\"style\":{\"fontFamily\":\"system-ui,\\\"Segoe UI\\\",Roboto,Helvetica,Arial,sans-serif,\\\"Apple Color Emoji\\\",\\\"Segoe UI Emoji\\\"\",\"height\":\"100vh\",\"textAlign\":\"center\",\"display\":\"flex\",\"flexDirection\":\"column\",\"alignItems\":\"center\",\"justifyContent\":\"center\"},\"children\":[\"$\",\"div\",null,{\"children\":[[\"$\",\"style\",null,{\"dangerouslySetInnerHTML\":{\"__html\":\"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}\"}}],[\"$\",\"h1\",null,{\"className\":\"next-error-h1\",\"style\":{\"display\":\"inline-block\",\"margin\":\"0 20px 0 0\",\"padding\":\"0 23px 0 0\",\"fontSize\":24,\"fontWeight\":500,\"verticalAlign\":\"top\",\"lineHeight\":\"49px\"},\"children\":\"404\"}],[\"$\",\"div\",null,{\"style\":{\"display\":\"inline-block\"},\"children\":[\"$\",\"h2\",null,{\"style\":{\"fontSize\":14,\"fontWeight\":400,\"lineHeight\":\"49px\",\"margin\":0},\"children\":\"This page could not be found.\"}]}]]}]}]],\"notFoundStyles\":[]}]}]}]],null],null],\"couldBeIntercepted\":false,\"initialHead\":[null,\"$La\"],\"globalErrorComponent\":\"$b\",\"missingSlots\":\"$Wc\"}]\n"])"""
            ),
            rx.script(
                """self.__next_f.push([1,"a:[[\"$\",\"meta\",\"0\",{\"name\":\"viewport\",\"content\":\"width=device-width, initial-scale=1\"}],[\"$\",\"meta\",\"1\",{\"charSet\":\"utf-8\"}],[\"$\",\"link\",\"2\",{\"rel\":\"icon\",\"href\":\"/favicon.ico\",\"type\":\"image/x-icon\",\"sizes\":\"16x16\"}],[\"$\",\"meta\",\"3\",{\"name\":\"next-size-adjust\"}]]\n5:null\n"])"""
            ),
            class_name="__className_3a0388 bg-background",
            _webkit_font_smoothing="antialiased",
            _moz_osx_font_smoothing="grayscale",
            font_family='system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
            min_height="100vh",
        ),
    )
